"""Initial_migration

Revision ID: 5af010037d9c
Revises:
Create Date: 2025-01-04 06:05:30.502627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5af010037d9c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Collect table names
    tables = inspector.get_table_names()

    # Drop each table with CASCADE
    for table in tables:
        conn.execute(sa.text(f"DROP TABLE IF EXISTS {table} CASCADE"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index("idx_users_discord_id", "users", ["discord_id"], unique=False)
    op.alter_column(
        "users", "discord_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
    )
    op.drop_column("users", "username")
    op.drop_column("users", "id")
    op.create_table(
        "schema_version",
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("version", name="schema_version_pkey"),
    )
    op.create_table(
        "bot_personality",
        sa.Column("personality_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column("personality_text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("category", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("personality_id", name="bot_personality_pkey"),
    )
    op.create_index(
        "idx_bot_personality_category", "bot_personality", ["category"], unique=False
    )
    op.create_table(
        "user_conversational_context",
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("context_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column("context_text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name="user_conversational_context_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint("context_id", name="user_conversational_context_pkey"),
    )
    op.create_index(
        "idx_user_conversational_context_user_id",
        "user_conversational_context",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "idx_user_conversational_context_timestamp",
        "user_conversational_context",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###
